version: '3'

services:
  eventstore.db:
    image: docker.eventstore.com/eventstore/eventstoredb-ee:24.10
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_NODE_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3639:80
    depends_on:
      - command
      - query

  command.db:
    restart: always
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=command
      - MONGO_INITDB_ROOT_PASSWORD=command

  command:
    restart: always
    build:
      context: ./command
      dockerfile: Dockerfile.dev
    environment:
      - EVENTSTORE_URL=esdb://eventstore.db:2113?tls=false
      - ME_CONFIG_MONGODB_ADMINUSERNAME=command
      - ME_CONFIG_MONGODB_ADMINPASSWORD=command
      - ME_CONFIG_MONGODB_URL=mongodb://command:command@command.db:27017/
      - ME_CONFIG_BASICAUTH=false
    volumes:
      - /app/node_modules
      - ./command:/app
    depends_on:
      - command.db
      - eventstore.db

  query.db:
    restart: always
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=query
      - MONGO_INITDB_ROOT_PASSWORD=query

  query:
    restart: always
    build:
      context: ./query
      dockerfile: Dockerfile.dev
    environment:
      - EVENTSTORE_URL=esdb://eventstore.db:2113?tls=false
      - ME_CONFIG_MONGODB_ADMINUSERNAME=query
      - ME_CONFIG_MONGODB_ADMINPASSWORD=query
      - ME_CONFIG_MONGODB_URL=mongodb://query:query@query.db:27017/
      - ME_CONFIG_BASICAUTH=false
    volumes:
      - /app/node_modules
      - ./query:/app
    depends_on:
      - query.db
      - eventstore.db

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
